source 'https://github.com/hyperledger/indy-sdk.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'indytest92' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for indy.test
  pod 'libindy-objc'

end
